# Server 02
[Interface]
PrivateKey = <Server02_Private_Key>
Address = 10.0.0.2/32
ListenPort = 51820

# Server 01
[Peer]
PublicKey = <Server01_Public_Key>
Endpoint = <Server01_Public_IP>:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25