# Phone/Laptop
[Interface]
PrivateKey = <Client_Private_Key>
Address = 10.0.0.3/32
DNS = 1.1.1.1

# Server (full internet though vpn)
[Peer]
PublicKey = <Server_Public_Key>
Endpoint = <Server_Public_IP>:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25