# Server 01
[Interface]
PrivateKey = <Server01_Private_Key>
Address = 10.0.0.1/24
ListenPort = 51820

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eno1 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eno1 -j MASQUERADE

# Server 02
[Peer]
PublicKey = <Server02_Public_Key>
AllowedIPs = 10.0.0.2/32

# Phone
[Peer]
PublicKey = <Client_Public_Key>
AllowedIPs = 10.0.0.3/32

# Laptop
[Peer]
PublicKey = <Client_Public_Key>
AllowedIPs = 10.0.0.4/32